# Generated by Django 2.2.5 on 2020-03-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='E_Person',
            new_name='P_Person',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='Por_Person',
            new_name='P_Person',
        ),
        migrations.RenameField(
            model_name='recent',
            old_name='R_Person',
            new_name='P_Person',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='S_Person',
            new_name='P_Person',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='W_Person',
            new_name='P_Person',
        ),
    ]
